trigger:
  batch: true

variables:
  testConfiguration: 'Debug'

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2019'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET'
    inputs:
      version: 5.0.x
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: restore
      restoreArguments: '--locked-mode'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'
  - task: DotNetCoreCLI@2
    displayName: 'Build Debug'
    inputs:
      command: build
      arguments: --no-restore --configuration Debug
  - task: DotNetCoreCLI@2
    displayName: 'Build Release'
    inputs:
      command: build
      arguments: --no-restore --configuration Release
  - task: DotNetCoreCLI@2
    displayName: 'Test Debug'
    inputs:
      command: test
      projects: 'NeoCoco.Tests/NeoCoco.Tests.csproj'
      arguments: --configuration $(testConfiguration) --logger "console;verbosity=detailed"
